# Generated by Django 5.0.1 on 2024-02-25 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='tag',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_tag', message='Tags must be a single word.', regex='^[a-zA-Z]+$'), django.core.validators.MinLengthValidator(1, message='Tag field cannot be empty.')]),
        ),
        migrations.AddField(
            model_name='idea',
            name='user_liked',
            field=models.BooleanField(default=False),
        ),
    ]
