# Generated by Django 5.0.1 on 2024-02-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_tag_idea_user_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_supported',
            field=models.BooleanField(default=False),
        ),
    ]
