# Generated by Django 5.0.1 on 2024-01-28 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='participants',
        ),
        migrations.AddField(
            model_name='team',
            name='supporters',
            field=models.ManyToManyField(related_name='supported_teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
