# Generated by Django 5.0.2 on 2024-02-18 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_invitation_invitation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='unreadmessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='unreadmessage',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='UnreadMessage',
        ),
    ]
