# Generated by Django 5.0.2 on 2024-02-15 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='Socials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regauth.socials'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regauth.works'),
        ),
    ]
