# Generated by Django 5.0.1 on 2024-01-29 03:37

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0002_customusers_ability_customusers_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
