# Generated by Django 5.0.2 on 2024-02-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
        ('regauth', '0002_customusers_socials_customusers_works'),
        ('team', '0003_remove_invitation_invitation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customusers',
            name='Socials',
        ),
        migrations.RemoveField(
            model_name='customusers',
            name='works',
        ),
        migrations.AddField(
            model_name='customusers',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='users', to='idea.idea'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='team.team'),
        ),
    ]
