# Generated by Django 5.0.1 on 2024-01-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0003_alter_customusers_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='link_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customusers',
            name='second_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
