# Generated by Django 5.0.2 on 2024-02-15 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0003_remove_customusers_socials_remove_customusers_works_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusers',
            name='socials',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regauth.socials'),
        ),
        migrations.AddField(
            model_name='customusers',
            name='works',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regauth.works'),
        ),
    ]
