# Generated by Django 5.0.2 on 2024-02-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
        ('regauth', '0004_customusers_socials_customusers_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusers',
            name='ideas',
            field=models.ManyToManyField(blank=True, related_name='idea', to='idea.idea'),
        ),
    ]
