# Generated by Django 5.0.2 on 2024-02-17 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0005_alter_customusers_ideas'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='works',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_works', to=settings.AUTH_USER_MODEL),
        ),
    ]
