# Generated by Django 5.0.2 on 2024-02-17 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0006_socials_user_works_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='user',
        ),
        migrations.RemoveField(
            model_name='works',
            name='user',
        ),
        migrations.AddField(
            model_name='socials',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_socials', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='works',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_works', to=settings.AUTH_USER_MODEL),
        ),
    ]
