# Generated by Django 5.0.1 on 2024-02-24 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0004_customusers_link_name_customusers_second_name_and_more'),
        ('regauth', '0007_remove_socials_user_remove_works_user_and_more'),
    ]

    operations = [
    ]
